// Generated by CoffeeScript 2.4.1
(function() {
  //'use strict';
  var demo;

  angular.module('myApp.homeView', ['ngRoute']).config([
    '$routeProvider',
    function($routeProvider) {
      return $routeProvider.when('/',
    {
        templateUrl: 'homeView/homeView.html',
        controller: 'View1Ctrl'
      });
    }
  ]).controller('View1Ctrl', [
    function() {
      return demo();
    }
  ]);

  demo = async function() {
    var data, opt, res, test;
    test = {
      hallo: 5,
      fast: "Da"
    };
    opt = {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(test)
    };
    res = (await fetch("http://localhost:4017/test", opt));
    data = (await res.json());
    return console.log(data);
  };

}).call(this);

//# sourceMappingURL=homeView.js.map
