// Generated by CoffeeScript 2.4.1
(function() {
  var app, express, port;

  express = require("express");

  app = express();

  port = 4017;

  app.use(express.static("../app"));

  app.use(express.json());

  app.get("/kA", function(req, res) {
    return res.send("Timestamp: " + Date.now());
  });

  app.listen(port, function() {
    return console.log(`Listening on port ${port}`);
  });

  app.post("/test", function(req, res) {
    console.log(req);
    console.log(req.body);
    return res.json({
      status: "succ",
      test: 5,
      jetzt: "Hier"
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
