// Generated by CoffeeScript 2.4.1
(function() {
  var app, express, parse, port, test;

  express = require("express");

  parse = require("csv-parse");

  app = express();

  port = 8080;

  app.use(express.static("../app"));

  app.use(express.json());

  app.listen(port, function() {
    return console.log(`Listening on port ${port}`);
  });

  app.get('/test', function(req, res) {
    var process, result, spawn;
    spawn = require('child_process').spawn;
    process = spawn('python', [
      './main.py',
      req.query.search, // pass data from
      req.query.type // GET method. Example: .../test?search=trump&type=1
    ]);
    result = "";
    process.stdout.on('data', function(data) {
      return result += data.toString();
    });
    return process.stdout.on('end', function() {
      console.log(result);
      return res.send(result);
    });
  });

  test = function() {
    var output, parser;
    output = [];
    parser = parse({
      delimiter: ':'
    });
    parser.on('readable', function() {
      var record, results;
      record = void 0;
      results = [];
      while ((record = parser.read())) {
        results.push(output.push(record));
      }
      return results;
    });
    parser.on('error', function(err) {
      return console.error(err.message);
    });
    parser.on('end', function() {
      return {};
    });
    parser.write("root:x:0:0:root:/root:/bin/bash\n");
    parser.write("someone:x:1022:1022::/home/someone:/bin/bash\n");
    parser.end();
    return console.log(output);
  };

  test();

}).call(this);

//# sourceMappingURL=index.js.map
