// Generated by CoffeeScript 2.4.1
(function() {
  var app, express, port;

  express = require("express");

  app = express();

  port = 8080;

  app.use(express.static("../app"));

  app.use(express.json());

  app.listen(port, function() {
    return console.log(`Listening on port ${port}`);
  });

  app.get('/test', function(req, res) {
    var process, result, spawn;
    console.log(req.query);
    spawn = require('child_process').spawn;
    process = spawn('python', [
      './main.py',
      req.query.search, // pass data from
      req.query.type // GET method. Example: .../test?search=trump&type=1
    ]);
    result = "";
    process.stdout.on('data', function(data) {
      return result += data.toString();
    });
    return process.stdout.on('end', function() {
      return res.send(result);
    });
  });

}).call(this);

//# sourceMappingURL=index.js.map
